language: python
python:
    - 2.7
   

cache: apt
before_install:
   - until sudo add-apt-repository -y ppa:saiarcot895/chromium-beta; do echo retry; done
   - until sudo add-apt-repository --yes ppa:kalakris/cmake; do echo retry; done
   - until sudo apt-get -qq update; do echo retry; done 
   - until sudo apt-get install cmake; do echo retry; done
   
install:
  - travis_retry pip install pysmt;
  - export LZ="$TRAVIS_BUILD_DIR/../zus"
  - mkdir -p $LZ
  - wget --output-document=zustre.tar.gz https://www.dropbox.com/s/cw29pcuglj867pp/zustre.tar.gz?dl=1;
  - tar xvf zustre.tar.gz --strip-components=1 -C $LZ;
  - ls $LZ

script:
  - mkdir -p build
  - cd build
  - /usr/bin/cmake -DLUSTREC_EXECUTABLE=$LZ/bin/lustrec -DZ3_ROOT=$LZ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=run -DCMAKE_PROGRAM_PATH=/usr/bin  ../;
  - /usr/bin/cmake --build .
  - /usr/bin/cmake --build . --target install 
  - cd ..
  - ls build/run/bin
  - ./build/run/bin/sygspacer -h 



notifications:
  email:
    recipients:
     - zustre-build@googlegroups.com
    on_success: always
    on_failure: always
