#!/usr/bin/env python

import sys
import os
import os.path
import threading
from multiprocessing import Process, Pool
import multiprocessing


def parseArgs (argv):
    import argparse as a
    p = a.ArgumentParser (description='\t SygSpacer -- Syntax based Invariant Synthesis')

    p.add_argument ('file', metavar='BENCHMARK', help='Benchmark file')
    p.add_argument ('--pp',
                    help='Enable default pre-processing',
                    action='store_true', default=False)
    p.add_argument ('--trace', help='Trace levels to enable',
                   default='')
    p.add_argument ('--stat', help='Print Spacer statistics', dest="stat",
                    default=False, action='store_true')
    p.add_argument ('--verbose', help='Verbose', action='store_true',
                    default=False, dest="verbose")
    p.add_argument ('--spacer_verbose', help='Spacer Verbose', action='store_true', default= False, dest='spacer_verbose')
    p.add_argument ('--ri', dest='ri', default=False, action='store_true',
                    help='Get Raw Invariants')
    p.add_argument ('--no-dl', help='Disable Difference Logic (UTVPI) in SPACER', action='store_true',
                    default=False, dest="utvpi")
    p.add_argument ('--timeout', help='Timeout',
                    type=float, default=20.0, dest="timeout")
    p.add_argument ('--solve', help='Solve Directly', action='store_true',
                    default=False, dest="solve")
    pars = p.parse_args (argv)
    return pars


def stat (key, val): stats.put (key, val)


def main (args):
    from sygspacer import Spacer
    import z3
    stat ('Result', 'UNKNOWN')
    ctx = z3.Context ()
    fp = z3.Fixedpoint (ctx=ctx)
    spacer = Spacer(args,ctx,fp)
    spacer.toHorn()


if __name__ == '__main__':
     # unbuffered output
    sys.stdout = os.fdopen (sys.stdout.fileno (), 'w', 0)
    path = os.path.abspath (sys.argv[0])
    path = os.path.dirname(path)

    ## update system PATH to location of the package
    if os.path.isdir (path):
        os.environ['PATH'] = path + os.pathsep + os.environ['PATH']

    path = os.path.abspath (os.path.join(path, '..', 'lib', 'sygspacerpy', 'src'))
    if os.path.isdir (path): sys.path.insert(0, path)
    z3_path = os.path.abspath (os.path.join(path, '..', '..', '..', 'lib', 'z3py'))
    if os.path.isdir (z3_path):   sys.path.insert(0, z3_path)
    print path
    import stats
    args = parseArgs(sys.argv[1:])
    try:
        p = multiprocessing.Process(target=main, args=(args,))
        p.start()
        p.join(args.timeout)
        if p.is_alive():
            stat('Result','TIMEOUT')
            stats.brunch_print()
            p.terminate()
            p.join()
        #main (args)
    except Exception as e:
        print str(e)
